# apiVersion: v1
# kind: Secret
# metadata:
#   name: redmine-api-secret
#   namespace: redmine
# type: Opaque
# stringData:
#   apiKey: "<redmine-api-key>"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: slack-webhook-secret
#   namespace: redmine
# type: Opaque
# stringData:
#   url: "<slack-webhook-url>"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: user-mapping-secret
#   namespace: redmine
# type: Opaque
# stringData:
#   mapping: '{"Redmine上の担当者名": "SlackのメンバーID"}'

